server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nirenxing/spring-cloud-config.git #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
      label: master #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

# 全局广播更新：localhost:3344/actuator/bus-refresh
# 定点更新，只更新3355： localhost:3344/actuator/bus-refresh/config-client:3355

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest


#  {label}/{name}-{profiles}
# label:分支  name：服务名  profiles:环境
#http://127.0.0.1:3344/master/config-dev.yml